In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.0.0
sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
matplotlib 3.1.1
numpy 1.17.2
pandas 0.25.1
sklearn 0.21.3
tensorflow 2.0.0
tensorflow_core.keras 2.2.4-tf


In [4]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
# index
display(t)
display(t[:, 1:])
display(t[..., 1]) # 第二列取出来作为一个单独的tensor
display(t[:, 1]) # 第二列取出来作为一个单独的tensor

<tf.Tensor: id=10, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

<tf.Tensor: id=14, shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

<tf.Tensor: id=18, shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

<tf.Tensor: id=22, shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [6]:
display(t +10)
display(tf.square(t))
display(t @ tf.transpose(t))

<tf.Tensor: id=26, shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

<tf.Tensor: id=27, shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

<tf.Tensor: id=30, shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [9]:
# numpy conversion
display(t.numpy())
display(np.square(t))
np_t = np.array([[1., 2., 3.], [4., 5., 6.]])
print(tf.constant(np_t))

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)


In [10]:
# Scalars
t = tf.constant(2.718)
print(t.numpy())
print(t.shape)

2.718
()


In [16]:
# strings
t= tf.constant('cafe')
display(t)
display(tf.strings.length(t))
display(tf.strings.length(t,unit='UTF8_CHAR'))
display(tf.strings.unicode_decode(t,'UTF8'))

<tf.Tensor: id=40, shape=(), dtype=string, numpy=b'cafe'>

<tf.Tensor: id=41, shape=(), dtype=int32, numpy=4>

<tf.Tensor: id=42, shape=(), dtype=int32, numpy=4>

<tf.Tensor: id=46, shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 101], dtype=int32)>

In [18]:
# strings array
t = tf.constant(['cafe','咖啡','coffee'])
display(tf.strings.length(t,unit='UTF8_CHAR'))
r = tf.strings.unicode_decode(t,'UTF8')
display(r)

<tf.Tensor: id=54, shape=(3,), dtype=int32, numpy=array([4, 2, 6], dtype=int32)>

<tf.RaggedTensor [[99, 97, 102, 101], [21654, 21857], [99, 111, 102, 102, 101, 101]]>

In [21]:
r = tf.ragged.constant([[11, 12], [21, 22, 23], [], [41]])
display(r)
display(r[1])
display(r[1:3])

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41]]>

<tf.Tensor: id=154, shape=(3,), dtype=int32, numpy=array([21, 22, 23], dtype=int32)>

<tf.RaggedTensor [[21, 22, 23], []]>

In [22]:
r2 = tf.ragged.constant([[51, 52], [], [71]])
tf.concat([r,r2],axis=0)

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41], [51, 52], [], [71]]>

In [24]:
r3 = tf.ragged.constant([[13, 14], [15], [100], [42, 43]])
print(tf.concat([r, r3], axis = 1))

<tf.RaggedTensor [[11, 12, 13, 14], [21, 22, 23, 15], [100], [41, 42, 43]]>


In [25]:
r.to_tensor()

<tf.Tensor: id=398, shape=(4, 3), dtype=int32, numpy=
array([[11, 12,  0],
       [21, 22, 23],
       [ 0,  0,  0],
       [41,  0,  0]], dtype=int32)>

In [34]:
s = tf.SparseTensor(# 稀疏矩阵
    indices = [[0, 1], [1, 0], [2, 3]], # 必须是排好序的，不然to_dense就会出错
                    values = [1., 2., 3.],
                    dense_shape = [3, 4]
                   )
display(s)

In [31]:
tf.sparse.to_dense(s)

<tf.Tensor: id=409, shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 3.]], dtype=float32)>

In [35]:
# sparse tensor
s5 = tf.SparseTensor(indices = [[0, 2], [0, 1], [2, 3]],
                    values = [1., 2., 3.],
                    dense_shape = [3, 4])
print(s5)
s6 = tf.sparse.reorder(s5) # reorder后就好了
print(tf.sparse.to_dense(s6))

SparseTensor(indices=tf.Tensor(
[[0 2]
 [0 1]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 2. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


In [33]:
# ops on sparse tensors

s2 = s * 2.0
print(s2)

try:
    s3 = s + 1 # sparse tensor 无法做 + 操作
except TypeError as ex:
    print(ex)

s4 = tf.constant([[10., 20.],
                  [30., 40.],
                  [50., 60.],
                  [70., 80.]])
print(tf.sparse.sparse_dense_matmul(s, s4))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
unsupported operand type(s) for +: 'SparseTensor' and 'int'
tf.Tensor(
[[ 30.  40.]
 [ 20.  40.]
 [210. 240.]], shape=(3, 2), dtype=float32)


In [38]:
# Variables
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
display(v) # Variable
display(v.value()) # output is tensor
display(v.numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

<tf.Tensor: id=456, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [39]:
v.assign(2*v)
display(v.numpy())
v[0, 1].assign(42)
display(v.numpy())
v[1].assign([7., 8., 9.])
display(v.numpy())

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)

array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)

array([[ 2., 42.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [40]:
# 你不能那么做
try:
    v[1] = [7., 8., 9.]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment
